### ISSUE TITLE
指纹，poc接口是否打算开发呢

### ISSUE THREAD

**Issue by Cturbo** [TophantTechnology/ARL#201]
指纹，poc接口是否打算开放呢？方便使用者按照指定格式批量导入

**Comment by 1c3z** [comment]
1. 添加PoC 可以  查看这个   [添加自定义poc](https://github.com/TophantTechnology/ARL/wiki/ARL-2.4-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#docker-%E7%8E%AF%E5%A2%83%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89poc)
2. 相关接口文档可以查看api/doc ， 或者抓包 
3. 指纹导入导出后期添加。

**Comment by OrangeKing-King** [comment]
自定义poc如何使用post

**Comment by 1c3z** [comment]
> 自定义poc如何使用post

其他额外参数参考requests
http_req(url, method='post')

**Comment by OrangeKing-King** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 指纹，poc接口是否打算开发呢 (#201)





  
自定义poc如何使用post
  
其他额外参数参考requests
 http_req(url, method='post')
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
